spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  application:
    name: task-manager-back
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/task-manager
#logging:
#  level:
#    org.hibernate.orm.jdbc.bind: trace